### ISSUE TITLE
How to set outAmount in JS api

### ISSUE THREAD

**Issue by yogiben** [coinapult/public#8]
`coinapult.js:207`

```
      receive: function(cb, amount, address, inCurrency, outCurrency, extOID, urlCallback) {
        var params = {'amount': amount};
        if (typeof address != 'undefined') {
          params.address = address;
        }
        if (typeof inCurrency != 'undefined') {
          params.currency = inCurrency;
        } else {
          params.currency = 'BTC';
        }
        if (typeof outCurrency != 'undefined') {
          params.outCurrency = outCurrency;
        }
        if (typeof extOID != 'undefined') {
          params.extOID = extOID;
        }
        if (typeof urlCallback != 'undefined') {
          params.callback = urlCallback;
        }

        return this.call('t/receive', params, true, true, cb);
      },
```

I want to set `outAmount` as in ` cli.receive(outAmount=100, outCurrency="EUR")`

how to set this? When I try and force it, it returns an error.

**Comment by isysd** [comment]
Hi thanks for letting us know about the issue. Basically outAmount just needed to be added as a parameter to the function you quote above. I did this and checked in the patch.

BTW, I don't believe javascript supports keyword arguments. You may have to specify your arguments in order, rather than by name. Like so:

cli.receive(cb, undefined, outAmount=100, undefined, undefined, outCurrency='EUR');
